### ISSUE TITLE
Enemies in coder's lab sometimes stop taking damage, especially the file explorer.

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [geckoking7/kgt_idle#12]
I can't check the inspect element menu because I am on a school device currently.

**Comment by geckoking7** [comment]
This is unblocked at your school?
I've experienced this with the ant and hoe but never on in coders lab.

**Comment by geckoking7** [comment]
Crtl-shift-C/Crtl-shift-V/F12 are some inspect shortcuts.
