### ISSUE TITLE
System upgrade in wfu makes day 2 impossible

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [geckoking7/kgt_idle#14]
Since you start on day 2 you don't have the gun and can't kill anything. which makes it impossible

**Comment by geckoking7** [comment]
Lol

**Comment by geckoking7** [comment]
No this was intentional. So you want me to tell you how or you think yourself?

**Comment by geckoking7** [comment]
If I tell you it'll seem obvious

**Comment by ExplodingHairyPotatoCat** [comment]
yeah what is it

**Comment by ExplodingHairyPotatoCat** [comment]
If it's using the emus that is really difficult

**Comment by geckoking7** [comment]
Let the imposter get hit by a car (only doable when they are found)

**Comment by ExplodingHairyPotatoCat** [comment]
And how do I find him then? Just hope he walks into a car???

**Comment by geckoking7** [comment]
No he follows you, so you have to be the master at baiting

**Comment by geckoking7** [comment]
Oh. Click on the HTP button for information on how to play
Basically press E to find who imposter

**Comment by geckoking7** [comment]
Okay next week's update I'll try to make some controls more obvious
