### ISSUE TITLE
Unable to get "door breaker" achievement

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [geckoking7/kgt_idle#17]
I already had entered zone 11, so the achievement won't trigger.

**Comment by geckoking7** [comment]
Oh I dum. Thanks for telling me

**Comment by geckoking7** [comment]
Have you actually defeated the door? The restriction to not fight the door is the same one that gives the achievement.

**Comment by ExplodingHairyPotatoCat** [comment]
Yes, I have. Currently grinding to beat the new enemy

**Comment by ExplodingHairyPotatoCat** [comment]
i was hovering over the achievement next to it because of lag, sorry for the confusion :/
