### ISSUE TITLE
able to infintely unequip green stick, which lowers my stats (too much, i lost like all of my stat progress because of this)

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [geckoking7/kgt_idle#19]
it happened after i equipped the bat from scout

**Comment by geckoking7** [comment]
Im sorry, Ill push out these two bug fixes. If you know what your stats before were, or roughy, I can make a weird code thing to reset it.

**Comment by ExplodingHairyPotatoCat** [comment]
I had roughly 6580 health, 3197 attack, and 742.5 regen (be aware these numbers could be wildly off, I used an equation that is reliant on memory to figure that out the values and my memory could be really faulty)

**Comment by geckoking7** [comment]
Ok, well the weird cheat code thing is as follows;
click on the calculator kills (on calculator page)
enter 'ephc'
The stats given are: 
7000 Hp 2000 A/D 400 R
Sorry for the issue :c
What formula where you using above?

**Comment by geckoking7** [comment]
That is very smart. I applaud you.
