### ISSUE TITLE
items stopped dropping, and left clicking deleted my gear. stones and usbs still drop.

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [geckoking7/kgt_idle#2]

**Comment by ExplodingHairyPotatoCat** [comment]
zone 6 and 7 guide books aren't appearing either.

**Comment by geckoking7** [comment]
Well I'll try and find how left clicking removes items, can you explain how items stop dropping (is it just equipable items?). Sorry about books 6 and 7, they don't exist yet.

I never knew people played this so thanks for this report :D

**Comment by ExplodingHairyPotatoCat** [comment]
yes, just equipable items are what isn't dropping and is deleted when I click on it. there is the possibility that I have gotten stupid unlucky, but everything else is dropping so i'm not sure.

**Comment by geckoking7** [comment]
Well, if your testing if equipable items drop, the sky has the highest items per drop rate. Does the items get deleted when something else is a equipped?

**Comment by ExplodingHairyPotatoCat** [comment]
when equipping it's fine. unequipping the items deletes them. if i click on the item when there's something in that spot, the item is deleted.

**Comment by geckoking7** [comment]
Ok, I'll try and fix that today.

**Comment by ExplodingHairyPotatoCat** [comment]
Just so you know I really like your game :)

**Comment by geckoking7** [comment]
You made my day already by simply saying something so thank you :D
Any ideas or any constructive criticism would be cool

**Comment by ExplodingHairyPotatoCat** [comment]
you could add the ability to see the cutscene pictures after closing them. I like the images :) you could also make it so that when you have a new item or something the button turns green. that way  you don't have to monitor the button to see when you get something

**Comment by geckoking7** [comment]
I was thinking on adding a way to see the lore pictures, I just feel embarrassed they exist. In the settings there is a way to make the inventory button flash when you get an item, and in the next update I'll be adding a loot filter.

**Comment by ExplodingHairyPotatoCat** [comment]
the drones feel a bit slow but that could just be me because I like things to be faster. maybe instead of rewatching the cutscenes, you can add a tutorial menu or something similar if you're embarrassed to see them.

**Comment by geckoking7** [comment]
I can speed up the base rate of the drones, it's just that they get exponentially more useful throughout the game. I just didn't know people liked the cutscenes.

**Comment by ExplodingHairyPotatoCat** [comment]
I might just be impatient, be sure to get other people's opinions.

**Comment by geckoking7** [comment]
Well if you could some of your friends...
(Please tell me you have friends because I don't)

**Comment by ExplodingHairyPotatoCat** [comment]
i'm not sure they like idle games, but ill ask them to play it  :)

**Comment by geckoking7** [comment]
That would be nice thanks :D

**Comment by geckoking7** [comment]
Can you tell me how you found the game?

**Comment by ExplodingHairyPotatoCat** [comment]
I went through the idle games page, which i tend to do to find games i like :)

**Comment by geckoking7** [comment]
Thank you

**Comment by geckoking7** [comment]
Fixed!
