### ISSUE TITLE
Somehow obtained -8 AP?

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [geckoking7/kgt_idle#8]
I bought the health upgrade, which lagged, so i clicked on it again, and when it unfroze it was at -8 ap. only worked when i had enough ap to start with

**Comment by ExplodingHairyPotatoCat** [comment]
to clarify, the upgrade didn't say that it cost -8 ap, but i had -8 ap

**Comment by geckoking7** [comment]
How much Ap do you have in total? (As I in points of achieves; green 1 blue 2 purple 3 yellow 4)

**Comment by geckoking7** [comment]
Also if you every find another error can you, inspect the page and if there is a little red X click on it and tell me what it was.

**Comment by geckoking7** [comment]
Well I fixed a bug relating to buying the drone upgrade perk, since I think that was causing the issue.

**Comment by ExplodingHairyPotatoCat** [comment]
> How much Ap do you have in total? (As I in points of achieves; green 1 blue 2 purple 3 yellow 4)

I think i had 2 AP beforehand.

**Comment by ExplodingHairyPotatoCat** [comment]
> Also if you every find another error can you, inspect the page and if there is a little red X click on it and tell me what it was.

Inspect element doesn't work on my devices for some reason.

**Comment by geckoking7** [comment]
Oh, well since the drone upgrade costs 2 and doesn't deduct any AP until you click on something else it allowed you to technically max it out even though AP could be negative. Fix for this is coming out on Sunday but the other perks should work.

**Comment by geckoking7** [comment]
Why can't you inspect the page?

**Comment by ExplodingHairyPotatoCat** [comment]
I figured it out, my drivers overwrote the inspect command, and right click didn't do anything for some reason, but I used the more tools command thingy to do it

**Comment by geckoking7** [comment]
Oh, the right click thing is intentional, you could also press crtl-shift-c or f12

**Comment by geckoking7** [comment]
It just helps a lot with bug fixing

**Comment by ExplodingHairyPotatoCat** [comment]
okay cool

**Comment by geckoking7** [comment]
:)
