### ISSUE TITLE
zone 9 unlock is broken

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [geckoking7/kgt_idle#9]
I killed all the enemies, and have the 4th drone, but it hasn't unlocked yet. the inspect menu shows nothing to help discover the issue. in case this matters, the drones I have are stickman, killer robots, feddy, and the sniper drone

**Comment by geckoking7** [comment]
Oh I mean it's coming next update

**Comment by geckoking7** [comment]
Sorry but I need to do some bug fixing before hand

**Comment by ExplodingHairyPotatoCat** [comment]
> Sorry but I need to do some bug fixing before hand

Oh okay thanks, I'll close the issue now
